# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCCaptureDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCCaptureDemo
  pod 'GoogleWebRTC', '~> 1.1.31999'
  pod 'abseil', '~> 1.20200923.2'
  pod 'SDWebImage/GIF'

  target 'OCCaptureDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCCaptureDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#use_modular_headers!
#install! 'cocoapods', :disable_input_output_paths => true
#
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if ['Spring'].include? target.name
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '4.2'
#            end
#        end
#        target.build_configurations.each do |config|
#            config.build_settings['ENABLE_BITCODE'] = 'NO'
#        end
#    end
#end
#
#target 'OCCaptureDemo' do
#  pod 'GoogleWebRTC', '~> 1.1.31999'
#  pod 'abseil', '~> 1.20200923.2'
#  pod 'SDWebImage/GIF'
#  target 'OCCaptureDemoTests' do
#      inherit! :search_paths
#      # Pods for testing
#  end
#
#  target 'OCCaptureDemoUITests' do
#      inherit! :search_paths
#      # Pods for testing
#  end
#
#end
