# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRTCVirtualBackgroundPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCVirtualBackgroundPOC
  pod 'GoogleWebRTC', '~> 1.1.31999'
  pod 'abseil', '~> 1.20200923.2'
  pod 'SDWebImage/GIF'

end
